### ISSUE TITLE
Add paper to repository

### ISSUE THREAD

**Issue by hanckmann** [znes/znes_cycle_detection#5]
I tried to lookup the refering paper to get more insight in how the algorithm works and how I can (should) use it. However, I could not find the paper online.
It would be great if there was a link to the PDF version of this paper, or if the PDF version of this paper was committed into this repository (in a docs folder or something).

Kind regards and thanks for sharing the code!

**Comment by fwitte** [comment]
Hi, very good point. Unfortunately, neither of us is the author of the paper. I'll contact the authors, if uploading the PDF in this repository is an option.

P.S.: Sent you an e-mail, regarding your request.

**Comment by hanckmann** [comment]
Hi,

I have already looked at reseachgate,  but the paper is not available for download there.
I have also requested the paper from the author there. I also checked https://arxiv.org, but the paper is also not available there...

I hope the author reacts to your or my request. If he reacts to my request I will let you know.

Patrick

**Comment by fwitte** [comment]
Hi again,
I checked, we unfortunately cannot directly add the PDF file here, but I added the link to the publication on ResearchGate in the corresponding of the README.
Best regards
